
server:
  port: 8004
spring:
  application:
    name: spring-cloud-config-git-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HoldDie/gitconfig/
          search-paths: configrepo
